import {
  typeBeast, typeElemental, typeHumanoid, typePlant, typeFey, typeUndead,
  alignmentUnaligned, alignmentNeutral, alignmentAny, alignmentChaoticNeutral,
  alignmentChaoticGood, alignmentChaoticEvil, alignmentNeutralGood,
  sizeTiny, sizeSmall, sizeMedium, sizeLarge, sizeHuge,
  reachShort, reachMediumShort, reachMedium,
  damageTypePiercing, damageTypeBludgeoning, damageTypeSlashing,
  damageTypeMundanePhysical, damageTypeMundanePiercingSlashing,
  damageTypeAcid, damageTypeCold, damageTypeFire, damageTypeLightning,
  damageTypeNecrotic, damageTypePoison, damageTypePsychic, damageTypeRadiant, damageTypeThunder,
  conditionExhaustion, conditionGrappled, conditionParalyzed, conditionPetrified,
  conditionPoisoned, conditionProne, conditionRestrained, conditionUnconscious,
  conditionCharmed, conditionFrightened, conditionBlinded,
  languageCreator, languageIgnan, languageCommon, languageDwarfish, languageElvish, languageSylvan,
  skillRankProficient, skillRankExpert,
  raceAny, genderFemale, genderNeutral,
  armorNatural,
} from '@toolkit5e/base';
import type { MonsterTemplate } from './types.js';

export const monsterList: Record<string, MonsterTemplate> = {
  ape: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: {
      attacks: {
        fist: { reach: reachMedium, damageType: damageTypeBludgeoning, name: 'Fist' },
        rock: { damageType: damageTypeBludgeoning, name: 'Rock', ranged: true },
      },
      skills: { athletics: skillRankProficient, perception: skillRankProficient },
      slug: 'ape',
      multiattack: { attacks: { fist: 2 } },
    },
    stats: {
      0.5: { name: 'Ape', hitDice: 3, speed: 30, climb: 30, size: sizeMedium, str: 16, dex: 14, con: 14, int: 6, wis: 12, cha: 7, attacks: { fist: { damageDice: 1, damageDieSize: 6 }, rock: { range: 25, longRange: 50, damageDice: 1, damageDieSize: 6 } } },
      7:   { name: 'Giant Ape', hitDice: 15, speed: 40, climb: 40, size: sizeHuge, str: 23, dex: 14, con: 18, int: 7, wis: 12, cha: 7, attacks: { fist: { damageDice: 3, damageDieSize: 10 }, rock: { range: 50, longRange: 100, damageDice: 7, damageDieSize: 6 } } },
    },
  },
  awakenedPlant: {
    name: 'Awakened Plant',
    type: typePlant,
    alignment: alignmentUnaligned,
    lockedStats: {
      armorDescription: armorNatural,
      int: 10,
      wis: 10,
      vulnerabilities: [damageTypeFire],
      languages: [languageCreator],
    },
    variants: {
      shrub: {
        name: 'Awakened Shrub',
        stats: { 0: { name: 'Awakened Shrub', attacks: { rake: { damageDice: 1, damageDieSize: 4 } } } },
        lockedStats: { slug: 'shrub', resistances: [damageTypePiercing], attacks: { rake: { reach: reachMediumShort, damageType: damageTypeSlashing, name: 'Rake', finesse: true } } },
      },
      tree: {
        name: 'Awakened Tree',
        stats: { 0: { name: 'Awakened Sapling' }, 2: { name: 'Awakened Tree', attacks: { slam: { damageDice: 3, damageDieSize: 6 } } } },
        lockedStats: { slug: 'tree', resistances: [damageTypeBludgeoning, damageTypePiercing], attacks: { slam: { reach: reachMediumShort, damageType: damageTypeBludgeoning, name: 'Slam' } } },
      },
    },
    traits: ['falseAppearance'],
    stats: {
      0: { bonusArmor: 0, speed: 20, hitDice: 3, size: sizeSmall, str: 3, dex: 8, con: 11, cha: 6 },
      2: { bonusArmor: 5, hitDice: 7, size: sizeHuge, str: 19, dex: 6, con: 15, cha: 7 },
    },
  },
  baboon: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { attacks: { bite: { reach: reachMedium, damageType: damageTypePiercing, name: 'Bite' } }, slug: 'baboon' },
    traits: ['packTactics'],
    stats: { 0: { name: 'Baboon', hitDice: 1, speed: 30, climb: 30, size: sizeSmall, str: 8, dex: 14, con: 11, int: 4, wis: 12, cha: 6, attacks: { bite: { damageDice: 1, damageDieSize: 4 } } } },
  },
  badger: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { attacks: { bite: { reach: reachMedium, damageType: damageTypePiercing, name: 'Bite', finesse: true } }, int: 2, slug: 'badger' },
    traits: ['keenSmell'],
    stats: {
      0:    { name: 'Badger', hitDice: 1, speed: 20, burrow: 5, size: sizeTiny, str: 4, dex: 11, con: 12, wis: 12, cha: 5, attacks: { bite: { damageDice: 1, damageDieSize: 1 } } },
      0.25: { name: 'Giant Badger', hitDice: 12, speed: 30, burrow: 10, size: sizeMedium, str: 13, dex: 10, con: 15, wis: 12, cha: 5, multiattack: { attacks: { bite: 1, claws: 1 } }, attacks: { bite: { damageDice: 1, damageDieSize: 6 }, claws: { reach: reachMedium, damageType: damageTypeSlashing, name: 'Claws', damageDice: 2, damageDieSize: 4 } } },
    },
  },
  bat: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { attacks: { bite: { reach: reachMedium, damageType: damageTypePiercing, name: 'Bite' } }, int: 2, blindsight: 60, slug: 'bat' },
    traits: ['keenHearing', 'echolocation'],
    stats: {
      0:    { name: 'Bat', hitDice: 1, speed: 5, fly: 30, size: sizeTiny, str: 2, dex: 15, con: 8, wis: 12, cha: 4, attacks: { bite: { damageDice: 1, damageDieSize: 1 } } },
      0.25: { name: 'Giant Bat', hitDice: 12, speed: 30, fly: 30, size: sizeMedium, str: 15, dex: 16, con: 11, wis: 12, cha: 6, attacks: { bite: { damageDice: 1, damageDieSize: 6 } } },
    },
  },
  camel: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { attacks: { bite: { reach: reachMedium, damageType: damageTypeBludgeoning, name: 'Bite' } }, int: 2, slug: 'camel' },
    stats: {
      0.125: { name: 'Camel', hitDice: 2, speed: 50, size: sizeLarge, str: 16, dex: 8, con: 14, wis: 8, cha: 5, attacks: { bite: { damageDice: 1, damageDieSize: 4 } } },
    },
  },
  boar: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: {
      attacks: { tusk: { reach: reachMedium, damageType: damageTypeSlashing, name: 'Tusk' } },
      int: 2,
      slug: 'boar',
    },
    traits: ['relentless', 'tramplingCharge'],
    stats: {
      0:    { name: 'Piglet' },
      0.25: { name: 'Boar',       hitDice: 2, speed: 40, size: sizeMedium, str: 13, dex: 11, con: 12, wis: 9, cha: 5, attacks: { tusk: { damageDice: 1, damageDieSize: 6 } }, traits: { relentless: { damageDice: 7, damageDieSize: 1 }, tramplingCharge: { chargeAttack: 'tusk', knockdownAttack: 'tusk', dcAdjustment: -4 } } },
      2:    { name: 'Giant Boar', hitDice: 5, speed: 40, size: sizeLarge,  str: 17, dex: 10, con: 16, wis: 9, cha: 5, attacks: { tusk: { damageDice: 2, damageDieSize: 6 } }, traits: { relentless: { damageDice: 10, damageDieSize: 1 }, tramplingCharge: { chargeAttack: 'tusk', knockdownAttack: 'tusk', dcAdjustment: -2 } } },
    },
  },
  bear: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: {
      armorDescription: armorNatural,
      attacks: {
        bite:  { reach: reachMedium, damageType: damageTypePiercing, name: 'Bite' },
        claws: { reach: reachMedium, damageType: damageTypeSlashing, name: 'Claws' },
      },
      multiattack: { attacks: { bite: 1, claws: 1 } },
      int: 2,
      slug: 'bear',
      speed: 40,
      skills: { perception: skillRankProficient },
    },
    traits: ['keenSmell'],
    stats: {
      0:   { name: 'Bear Cub' },
      0.5: { name: 'Black Bear', hitDice: 3, bonusArmor: 1, size: sizeMedium, str: 15, con: 14, climb: 30, attacks: { bite: { damageDice: 1, damageDieSize: 6 }, claws: { damageDice: 2, damageDieSize: 4 } } },
      1:   { name: 'Brown Bear', hitDice: 4, bonusArmor: 1, size: sizeLarge,  str: 19, con: 16, climb: 30, attacks: { bite: { damageDice: 1, damageDieSize: 8 }, claws: { damageDice: 2, damageDieSize: 6 } } },
      2:   { name: 'Polar Bear', hitDice: 5, bonusArmor: 2, size: sizeLarge,  str: 20, con: 16, swim: 30,  attacks: { bite: { damageDice: 1, damageDieSize: 8 }, claws: { damageDice: 2, damageDieSize: 6 } } },
    },
  },
  commoner: {
    type: typeHumanoid,
    alignment: alignmentAny,
    race: raceAny,
    gender: genderNeutral,
    lockedStats: { attacks: { club: { reach: reachMedium, damageType: damageTypeBludgeoning, name: 'Club' } }, extraLanguages: 1, slug: 'commoner', size: sizeMedium },
    stats: { 0: { name: 'Commoner', hitDice: 1, speed: 30, str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10, attacks: { club: { damageDice: 1, damageDieSize: 4 } } } },
  },
  crocodile: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { armorDescription: armorNatural, int: 2, slug: 'crocodile', attacks: { bite: { reach: reachShort, damageType: damageTypePiercing, name: 'Bite', proc: 'grappleBite' } }, skills: { stealth: skillRankExpert } },
    traits: ['holdBreath'],
    stats: {
      0.5: { name: 'Crocodile', bonusArmor: 2, hitDice: 3, speed: 20, swim: 30, size: sizeLarge, str: 15, dex: 10, con: 13, wis: 10, cha: 5, attacks: { bite: { damageDice: 1, damageDieSize: 10 } }, traits: { holdBreath: { duration: 15 } } },
      5:   { name: 'Giant Crocodile', bonusArmor: 5, hitDice: 9, speed: 30, swim: 50, size: sizeHuge, str: 21, dex: 9, con: 17, wis: 10, cha: 7, multiattack: { attacks: { bite: 1, tail: 1 } }, attacks: { bite: { damageDice: 3, damageDieSize: 10 }, tail: { reach: reachMediumShort, damageType: damageTypeBludgeoning, name: 'Tail', proc: 'takeDown', damageDice: 2, damageDieSize: 8, notGrappled: true } }, traits: { holdBreath: { duration: 30 } } },
    },
  },
  dolphinDelighter: {
    name: 'Dolphin Delighter',
    type: typeFey,
    alignment: alignmentChaoticGood,
    lockedStats: { armorDescription: armorNatural, attacks: { dazzlingSlam: { reach: reachShort, damageType: damageTypeBludgeoning, damageRiderType: damageTypePsychic, name: 'Dazzling Slam', proc: 'conditionNoSave' } }, multiattack: { attacks: { dazzlingSlam: 2 } }, skills: { perception: skillRankProficient, performance: skillRankProficient }, slug: 'dolphin' },
    bonusActions: ['delightfulLight', 'feyLeap'],
    traits: ['holdBreath'],
    stats: {
      3: { name: 'Dolphin Delighter', bonusArmor: 3, blindsight: 60, hitDice: 5, speed: 0, swim: 60, size: sizeMedium, str: 14, dex: 13, con: 13, int: 11, wis: 12, cha: 16, attacks: { dazzlingSlam: { damageDice: 1, damageDieSize: 6, damageRiderDice: 2, damageRiderDieSize: 6 } }, traits: { conditionNoSave: { condition: 'blinded' }, delightfulLight: { damageDice: 2, damageDieSize: 10 }, holdBreath: { duration: 20 } } },
    },
  },
  dryad: {
    type: typeFey,
    alignment: alignmentNeutral,
    lockedStats: {
      attacks: { club: { reach: reachMedium, damageType: damageTypeBludgeoning, name: 'Club' } },
      castingStat: 'cha',
      gender: genderFemale,
      languages: [languageElvish, languageSylvan],
      skills: { perception: skillRankProficient, stealth: skillRankProficient },
      slug: 'dryad',
      size: sizeMedium,
      traits: { innateSpellcasting: { spellList: { druidcraft: { uses: 0 }, entangle: { uses: 3 }, goodberry: { uses: 3 }, barkskin: { uses: 1 }, passWithoutTrace: { uses: 1 }, shillelagh: { uses: 1 } } } },
    },
    actions: ['feyCharm'],
    traits: ['innateSpellcasting', 'magicResistance', 'speakWithBeastsAndPlants', 'treeStride'],
    stats: { 1: { name: 'Dryad', hitDice: 5, speed: 30, str: 10, dex: 12, con: 11, int: 14, wis: 15, cha: 18, attacks: { club: { damageDice: 1, damageDieSize: 4 } } } },
  },
  elephant: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { armorDescription: armorNatural, attacks: { gore: { reach: reachShort, damageType: damageTypePiercing, name: 'Gore' }, stomp: { reach: reachShort, damageType: damageTypeBludgeoning, name: 'Stomp', proneOnly: true } }, int: 3 },
    traits: ['tramplingCharge'],
    variants: {
      elephant: {
        name: 'Elephant',
        lockedStats: { int: 3 },
        stats: { 4: { slug: 'elephant', name: 'Elephant', speed: 40, cha: 6 }, 6: { slug: 'mammoth', name: 'Mammoth', cha: 6 } },
      },
      triceratops: {
        name: 'Triceratops',
        lockedStats: { int: 2 },
        stats: { 5: { slug: 'triceratops', name: 'Triceratops', speed: 50, cha: 5 } },
      },
    },
    stats: {
      4: { bonusArmor: 3, hitDice: 8, size: sizeHuge, str: 22, dex: 9, con: 17, wis: 11, traits: { tramplingCharge: { dcAdjustment: -4 } }, attacks: { gore: { damageDice: 3, damageDieSize: 8 }, stomp: { damageDice: 3, damageDieSize: 10 } } },
      5: { bonusArmor: 4, hitDice: 10, size: sizeHuge, str: 22, dex: 9, con: 17, wis: 11, traits: { tramplingCharge: { dcAdjustment: -4 } }, attacks: { gore: { damageDice: 4, damageDieSize: 8 }, stomp: { damageDice: 3, damageDieSize: 10 } } },
      6: { bonusArmor: 4, hitDice: 11, size: sizeHuge, str: 24, dex: 9, con: 21, wis: 11, traits: { tramplingCharge: { dcAdjustment: 0 } }, attacks: { gore: { damageDice: 4, damageDieSize: 8, reach: reachMediumShort }, stomp: { damageDice: 4, damageDieSize: 10 } } },
    },
  },
  giantSpider: {
    name: 'Giant Spider',
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: {
      armorDescription: armorNatural,
      attacks: {
        bite: { reach: reachMedium, damageType: damageTypePiercing, name: 'Bite', proc: 'poisonBite' },
      },
      int: 2,
      blindsight: 10,
      darkvision: 60,
      slug: 'giantSpider',
      skills: { stealth: skillRankExpert },
    },
    traits: ['spiderClimb', 'webSense', 'webWalker'],
    actions: ['web'],
    stats: {
      1: { name: 'Giant Spider', hitDice: 4, bonusArmor: 4, speed: 30, climb: 30, size: sizeLarge, str: 14, dex: 16, con: 12, wis: 11, cha: 4, attacks: { bite: { damageDice: 1, damageDieSize: 8 } } },
    },
  },
  horse: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: {
      attacks: { hooves: { reach: reachMedium, damageType: damageTypeBludgeoning, name: 'Hooves' } },
      int: 2,
      size: sizeLarge,
      slug: 'horse',
    },
    variants: {
      riding: {
        name: 'Riding Horse',
        stats: {
          0:    { name: 'Foal' },
          0.25: { name: 'Riding Horse', hitDice: 2, speed: 60, str: 16, attacks: { hooves: { damageDice: 2, damageDieSize: 4 } } },
        },
      },
      draft: {
        name: 'Draft Horse',
        stats: {
          0:    { name: 'Foal' },
          0.25: { name: 'Draft Horse', hitDice: 3, speed: 40, str: 18, attacks: { hooves: { damageDice: 2, damageDieSize: 4 } } },
        },
      },
      war: {
        name: 'Warhorse',
        traits: ['tramplingCharge'],
        lockedStats: { slug: 'warhorse', bonusArmor: 1 },
        stats: {
          0:   { name: 'Foal' },
          0.5: { name: 'Warhorse', hitDice: 3, speed: 60, str: 18, attacks: { hooves: { damageDice: 2, damageDieSize: 6 } }, traits: { tramplingCharge: { chargeAttack: 'hooves', knockdownAttack: 'hooves' } } },
          4:   { name: 'Destrier' },
        },
      },
    },
    stats: {
      0.25: { hitDice: 2, speed: 60, str: 16, dex: 10, con: 12, wis: 11, cha: 7, attacks: { hooves: { damageDice: 2, damageDieSize: 4 } } },
      0.5:  { hitDice: 3, speed: 60, str: 18, dex: 12, con: 13, wis: 12, cha: 7, attacks: { hooves: { damageDice: 2, damageDieSize: 6 } }, traits: { tramplingCharge: { chargeAttack: 'hooves', knockdownAttack: 'hooves' } } },
    },
  },
  eagle: {
    type: typeBeast,
    alignment: alignmentNeutralGood,
    lockedStats: {
      attacks: {
        beak:   { reach: reachMedium, damageType: damageTypePiercing, name: 'Beak' },
        talons: { reach: reachMedium, damageType: damageTypeSlashing, name: 'Talons' },
      },
      slug: 'eagle',
      skills: { perception: skillRankProficient },
    },
    traits: ['keenSight'],
    stats: {
      0: { name: 'Eaglet' },
      0.125: { name: 'Eagle',       hitDice: 1, speed: 10, fly: 60, size: sizeSmall,  str: 6,  dex: 15, con: 10, int: 2, wis: 14, cha: 7,  attacks: { talons: { damageDice: 1, damageDieSize: 4 } } },
      1:     { name: 'Giant Eagle', hitDice: 4, speed: 10, fly: 80, size: sizeLarge,  str: 16, dex: 17, con: 13, int: 8, wis: 14, cha: 10, multiattack: { attacks: { beak: 1, talons: 1 } }, attacks: { beak: { damageDice: 1, damageDieSize: 6 }, talons: { damageDice: 2, damageDieSize: 6 } }, languages: ['Giant Eagle'] },
    },
  },
  fireElemental: {
    name: 'Fire Elemental',
    type: typeElemental,
    alignment: alignmentNeutral,
    lockedStats: { darkvision: 60, languages: [languageIgnan], resistances: [damageTypeMundanePhysical], immunities: [damageTypeFire, damageTypePoison], conditionImmunities: [conditionExhaustion, conditionGrappled, conditionParalyzed, conditionPetrified, conditionPoisoned, conditionProne, conditionRestrained, conditionUnconscious], attacks: { touch: { reach: reachMediumShort, damageType: damageTypeFire, name: 'Touch', proc: 'ignite' } }, slug: 'elemental', multiattack: { attacks: { touch: 2 } } },
    traits: ['fireForm', 'illumination', 'waterSusceptibility'],
    stats: { 5: { name: 'Fire Elemental', hitDice: 12, speed: 50, size: sizeLarge, str: 10, dex: 17, con: 16, int: 6, wis: 10, cha: 7, attacks: { touch: { damageDice: 2, damageDieSize: 6, finesse: true } }, traits: { ignite: { damageDice: 1, damageDieSize: 10 }, fireForm: { damageDice: 1, damageDieSize: 10 }, waterSusceptibility: { damageDice: 1, damageDieSize: 1 } } } },
  },
  killerWhale: {
    name: 'Killer Whale',
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { armorDescription: armorNatural, attacks: { bite: { reach: reachShort, damageType: damageTypePiercing, name: 'Bite' } }, int: 3, skills: { perception: skillRankProficient }, slug: 'whale' },
    traits: ['echolocation', 'holdBreath', 'keenHearing'],
    stats: { 3: { name: 'Killer Whale', bonusArmor: 2, blindsight: 120, hitDice: 12, speed: 0, swim: 60, size: sizeHuge, str: 19, dex: 10, con: 13, wis: 12, cha: 7, attacks: { bite: { damageDice: 5, damageDieSize: 6 } }, traits: { holdBreath: { duration: 30 } } } },
  },
  naiad: {
    type: typeFey,
    alignment: alignmentChaoticNeutral,
    lockedStats: {
      armorDescription: armorNatural,
      attacks: { psychicTouch: { reach: reachMedium, damageType: damageTypePsychic, name: 'Psychic Touch', spellAttack: true } },
      castingStat: 'cha',
      languages: [languageCommon, languageSylvan],
      resistances: [damageTypePsychic],
      immunities: [damageTypePoison],
      conditionImmunities: [conditionCharmed, conditionFrightened, conditionPoisoned],
      skills: { persuasion: skillRankProficient, sleightOfHand: skillRankProficient },
      slug: 'naiad',
      size: sizeMedium,
      traits: { innateSpellcasting: { spellList: { minorIllusion: { uses: 0 }, phantasmalForce: { uses: 3 }, fly: { uses: 1 }, hypnoticPattern: { uses: 1 } } } },
      multiattack: { attacks: { psychicTouch: 2 } },
    },
    traits: ['amphibious', 'invisibleInWater', 'innateSpellcasting', 'magicResistance'],
    stats: { 2: { name: 'Naiad', bonusArmor: 2, hitDice: 7, speed: 30, swim: 30, str: 10, dex: 16, con: 11, int: 15, wis: 10, cha: 18, attacks: { psychicTouch: { damageDice: 1, damageDieSize: 10 } } } },
  },
  quetzalcoatlus: {
    type: typeBeast,
    subtype: 'dinosaur',
    alignment: alignmentUnaligned,
    lockedStats: { int: 2, skills: { perception: skillRankProficient }, attacks: { bite: { reach: reachShort, damageType: damageTypePiercing, name: 'Bite', proc: 'flyingCharge' } } },
    traits: ['flyby'],
    stats: {
      2: { name: 'Quetzalcoatlus', size: sizeHuge, hitDice: 4, str: 15, dex: 13, con: 13, wis: 10, cha: 5, slug: 'quetzalcoatlus', speed: 10, fly: 80, attacks: { bite: { damageDice: 3, damageDieSize: 6 } }, traits: { flyingCharge: { damageDice: 3, damageDieSize: 6 } } },
      8: { name: 'Hatzegopteryx', slug: 'hatzegopteryx' },
    },
  },
  saberToothedTiger: {
    name: 'Saber-Toothed Tiger',
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { slug: 'tiger', int: 3, skills: { perception: skillRankProficient, stealth: skillRankExpert }, attacks: { bite: { reach: reachShort, damageType: damageTypePiercing, name: 'Bite' }, claw: { reach: reachShort, damageType: damageTypeSlashing, name: 'Claw' } } },
    traits: ['keenSmell', 'pounce'],
    stats: { 2: { name: 'Saber-Toothed Tiger', size: sizeLarge, hitDice: 7, str: 18, dex: 14, con: 15, wis: 12, cha: 8, speed: 40, attacks: { bite: { damageDice: 1, damageDieSize: 10 }, claw: { damageDice: 2, damageDieSize: 6 } } } },
  },
  shadow: {
    alignment: alignmentChaoticEvil,
    type: typeUndead,
    lockedStats: { attacks: { strengthDrain: { reach: reachMedium, damageType: damageTypeNecrotic, name: 'Strength Drain', finesse: true, proc: 'strengthDrain' } }, conditionImmunities: [conditionExhaustion, conditionFrightened, conditionGrappled, conditionParalyzed, conditionPetrified, conditionPoisoned, conditionProne, conditionRestrained], immunities: [damageTypeNecrotic, damageTypePoison], resistances: [damageTypeAcid, damageTypeCold, damageTypeFire, damageTypeLightning, damageTypeThunder], skills: { stealth: skillRankProficient }, slug: 'shadow' },
    traits: ['amorphous', 'shadowStealth', 'sunlightWeakness'],
    variants: {
      shadow: { name: 'Shadow', type: typeUndead, lockedStats: { resistances: [damageTypeMundanePhysical], vulnerabilities: [damageTypeRadiant] }, stats: { 2: { name: 'Shadow' } } },
      detachedShadow: { name: 'Detached Shadow', type: typeFey, lockedStats: { resistances: [damageTypeMundanePhysical], vulnerabilities: [damageTypeRadiant] }, stats: { 2: { name: 'Detached Shadow' } } },
      reflection: { name: 'Reflection', type: typeFey, lockedStats: { slug: 'reflection', resistances: [damageTypeMundanePiercingSlashing], vulnerabilities: [damageTypeBludgeoning] }, stats: { 2: { name: 'Reflection' } } },
    },
    stats: { 2: { hitDice: 3, speed: 40, size: sizeMedium, str: 6, dex: 14, con: 13, int: 6, wis: 10, cha: 8, attacks: { strengthDrain: { damageDice: 2, damageDieSize: 6 } } } },
  },
  shark: {
    name: 'Shark',
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { armorDescription: armorNatural, attacks: { bite: { reach: reachShort, damageType: damageTypePiercing, name: 'Bite' } }, int: 1, skills: { perception: skillRankProficient }, slug: 'shark' },
    traits: ['waterBreathing'],
    variants: {
      frenzy:     { name: 'Bloody Frenzy',  traits: ['bloodyFrenzy'],  stats: { 0.5: { name: 'Small Hunter Shark' }, 2: { name: 'Hunter Shark' } } },
      packHunter: { name: 'Pack Hunter',    traits: ['packTactics'],   stats: { 0.5: { name: 'Reef Shark' },        2: { name: 'Large Reef Shark' } } },
    },
    stats: {
      0.5: { bonusArmor: 1, hitDice: 4, swim: 40, size: sizeMedium, str: 14, dex: 13, con: 13, wis: 10, cha: 4, attacks: { bite: { damageDice: 1, damageDieSize: 8 } } },
      2:   { bonusArmor: 1, hitDice: 6, swim: 40, size: sizeLarge,  str: 18, dex: 13, con: 15, wis: 10, cha: 4, attacks: { bite: { damageDice: 2, damageDieSize: 8 } } },
      5:   { name: 'Giant Shark', bonusArmor: 3, hitDice: 11, swim: 50, size: sizeHuge, str: 23, dex: 11, con: 21, wis: 10, cha: 5, attacks: { bite: { damageDice: 3, damageDieSize: 10 } } },
    },
  },
  trex: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { armorDescription: armorNatural, attacks: { bite: { reach: reachMedium, proc: 'grappleBiteSizeRestricted', damageType: damageTypePiercing, name: 'Bite' }, tail: { reach: reachMedium, damageType: damageTypeBludgeoning, name: 'Tail' } }, int: 2, skills: { perception: skillRankProficient }, slug: 'tyrannosaurus', multiattack: { attacks: { bite: 1, tail: 1 }, requireDifferentTargets: true } },
    stats: { 8: { name: 'Tyrannosaurus Rex', bonusArmor: 3, hitDice: 13, speed: 50, size: sizeHuge, str: 25, dex: 10, con: 19, wis: 12, cha: 9, attacks: { bite: { damageDice: 4, damageDieSize: 12 }, tail: { damageDice: 3, damageDieSize: 8 } }, traits: { grappleBiteSizeRestricted: { dcAdjustment: -1, sizeAdjustment: -2 } } } },
  },
  wolf: {
    type: typeBeast,
    alignment: alignmentUnaligned,
    lockedStats: { armorDescription: armorNatural, attacks: { bite: { reach: reachShort, proc: 'takeDown', damageType: damageTypePiercing, name: 'Bite', finesse: true } }, int: 3, skills: { perception: skillRankProficient, stealth: skillRankProficient }, slug: 'wolf' },
    traits: ['keenHearingSmell', 'packTactics'],
    stats: {
      0:    { name: 'Wolf Pup' },
      0.25: { name: 'Wolf',      bonusArmor: 1, hitDice: 2, speed: 40, size: sizeMedium, str: 12, dex: 15, con: 12, wis: 12, cha: 6, attacks: { bite: { damageDice: 2, damageDieSize: 4 } } },
      1:    { name: 'Dire Wolf', bonusArmor: 2, hitDice: 5, speed: 50, size: sizeLarge,  str: 17, dex: 15, con: 15, wis: 12, cha: 7, attacks: { bite: { damageDice: 2, damageDieSize: 6 } } },
      20:   { name: 'Legendary Wolf' },
    },
  },
};
